version: "3.3"
services:
  webserver:
    build: ./webservice/server
    ports:
      - 3001:3001
      - 3002:3002
    networks: 
      - project-network
    command: npm run start
  webui:
    build: ./webservice/ui
    ports:
      - 3000:3000
    networks:
      - project-network 
    command: npm run dev
networks:
  project-network:
    driver: bridge
