version: "3.3"
services:
  ffserver:
    build: ./ffmpeg
    ports:
      - "3004:3004"
    networks:
      - project-network
    volumes:
      - ./resources:/resources
    # command: ffserver ffmpeg -re -i /resources/Pedestrian_Detect_2_1_1.mp4 http://localhost:3004/feed.ffm
  webserver:
    build: ./webservice/server
    ports:
      - 3001:3001
      - 3002:3002
    networks:
      - project-network
    command: npm run start
  webui:
    build: ./webservice/ui
    ports:
      - 3000:3000
    networks:
      - project-network
    command: npm run dev
  inferemce:
    build:
      context: ./inference
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    env_file:
    - .env  
    networks:
      - project-network
    depends_on:
      - webserver
    restart: on-failure
    volumes:
      - "./inference/wait-for-it.sh:/app/wait-for-it.sh"
      - "./inference/app/main.py:/app/main.py"
      - "./inference/app/inference.py:/app/inference.py"
      - "./inference/data:/app/data"
      - "./inference/run-inference-commands.sh:/app/run-inference-commands.sh"
    command:
      [
        "/app/wait-for-it.sh",
        "webserver:3001",
        "--",
        "/app/run-inference-commands.sh"
      ]

networks:
  project-network:
    driver: bridge
