version: "3.3"
services:
  ffserver:
    build: ./ffmpeg
    ports:
      - "3004:3004"
    networks:
      - project-network
    volumes:
      - ./resources:/resources  
    # command: ffserver ffmpeg -re -i /resources/Pedestrian_Detect_2_1_1.mp4 http://localhost:3004/feed.ffm
  webserver:
    build: ./webservice/server
    ports:
      - 3001:3001
      - 3002:3002
    networks:
      - project-network
    command: npm run start
  webui:
    build: ./webservice/ui
    ports:
      - 3000:3000
    networks:
      - project-network
    command: npm run dev
  inferemce:
    build: ./inference
    ports:
      - 3003:3003
    networks:
      - project-network
    depends_on:
      - webserver
    restart: on-failure
    # command: model-downloader --print_all
    command: ["./wait-for-it.sh", "webserver:3001", "--", "python", "main.py"]

networks:
  project-network:
    driver: bridge
